apiVersion: v1
kind: Service
metadata:
  name: kvstore
  namespace: kvstore
  labels:
    app: kvstore
spec:
  clusterIP: None
  ports:
    - name: rpc
      port: 5003
      targetPort: 5003
    - name: health
      port: 8080
      targetPort: 8080
  selector:
    app: kvstore
